// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace es.efor.PryBase.Data.Database
{
    public partial class Details
    {
        public Details()
        {
            Permissions = new HashSet<Permissions>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Functionality { get; set; }

        public virtual Functionalities FunctionalityNavigation { get; set; }
        public virtual ICollection<Permissions> Permissions { get; set; }
    }
}