// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace es.efor.PryBase.Data.Database
{
    public partial class Modules
    {
        public Modules()
        {
            Functionalities = new HashSet<Functionalities>();
            LogImports = new HashSet<LogImports>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Functionalities> Functionalities { get; set; }
        public virtual ICollection<LogImports> LogImports { get; set; }
    }
}