// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace es.efor.PryBase.Data.Database
{
    public partial class Permissions
    {
        public int Id { get; set; }
        public int Functionality { get; set; }
        public int Detail { get; set; }
        public bool Enabled { get; set; }
        public int Department { get; set; }
        public int Level { get; set; }

        public virtual UserDepartment DepartmentNavigation { get; set; }
        public virtual Details DetailNavigation { get; set; }
        public virtual Functionalities FunctionalityNavigation { get; set; }
        public virtual UserLevel LevelNavigation { get; set; }
    }
}