// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace es.efor.PryBase.Infraestructure.Database
{
    public partial class Project
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int ResponsableId { get; set; }
        public int PriorityType { get; set; }
        [Column("DStart", TypeName = "date")]
        public DateTime Dstart { get; set; }
        [Column("DEnd", TypeName = "date")]
        public DateTime Dend { get; set; }

        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(Employee.Project))]
        public virtual Employee IdNavigation { get; set; }
        public virtual Employee Responsable { get; set; }
    }
}