### YamlMime:ManagedReference
items:
- uid: es.efor.Auth.Extensions.IApplicationBuilderExtensions
  commentId: T:es.efor.Auth.Extensions.IApplicationBuilderExtensions
  id: IApplicationBuilderExtensions
  parent: es.efor.Auth.Extensions
  children:
  - es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforIdentityAuthentication``7(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  - es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforSimpleAuthentication``2(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  langs:
  - csharp
  - vb
  name: IApplicationBuilderExtensions
  nameWithType: IApplicationBuilderExtensions
  fullName: es.efor.Auth.Extensions.IApplicationBuilderExtensions
  type: Class
  source:
    remote:
      path: es.efor.Auth/Extensions/IApplicationBuilderExtensions.cs
      branch: master
      repo: https://dev.azure.com/EforDevelop/Musaat/_git/Musaat_Med
    id: IApplicationBuilderExtensions
    path: ../es.efor.Auth/Extensions/IApplicationBuilderExtensions.cs
    startLine: 10
  assemblies:
  - es.efor.Auth
  namespace: es.efor.Auth.Extensions
  syntax:
    content: public static class IApplicationBuilderExtensions
    content.vb: Public Module IApplicationBuilderExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforSimpleAuthentication``2(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  commentId: M:es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforSimpleAuthentication``2(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  id: UseEforSimpleAuthentication``2(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  isExtensionMethod: true
  parent: es.efor.Auth.Extensions.IApplicationBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseEforSimpleAuthentication<TAccountController, TAccessController>(IApplicationBuilder)
  nameWithType: IApplicationBuilderExtensions.UseEforSimpleAuthentication<TAccountController, TAccessController>(IApplicationBuilder)
  fullName: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforSimpleAuthentication<TAccountController, TAccessController>(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  type: Method
  source:
    remote:
      path: es.efor.Auth/Extensions/IApplicationBuilderExtensions.cs
      branch: master
      repo: https://dev.azure.com/EforDevelop/Musaat/_git/Musaat_Med
    id: UseEforSimpleAuthentication
    path: ../es.efor.Auth/Extensions/IApplicationBuilderExtensions.cs
    startLine: 12
  assemblies:
  - es.efor.Auth
  namespace: es.efor.Auth.Extensions
  syntax:
    content: >-
      public static IApplicationBuilder UseEforSimpleAuthentication<TAccountController, TAccessController>(this IApplicationBuilder app)

          where TAccountController : AccountSimpleController where TAccessController : AccessController
    parameters:
    - id: app
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    typeParameters:
    - id: TAccountController
    - id: TAccessController
    return:
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseEforSimpleAuthentication(Of TAccountController As AccountSimpleController, TAccessController As AccessController)(app As IApplicationBuilder) As IApplicationBuilder
  overload: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforSimpleAuthentication*
  nameWithType.vb: IApplicationBuilderExtensions.UseEforSimpleAuthentication(Of TAccountController, TAccessController)(IApplicationBuilder)
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforSimpleAuthentication(Of TAccountController, TAccessController)(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  name.vb: UseEforSimpleAuthentication(Of TAccountController, TAccessController)(IApplicationBuilder)
- uid: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforIdentityAuthentication``7(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  commentId: M:es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforIdentityAuthentication``7(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  id: UseEforIdentityAuthentication``7(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  isExtensionMethod: true
  parent: es.efor.Auth.Extensions.IApplicationBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseEforIdentityAuthentication<TKey, TUser, TRole, TSignInManager, TUserManager, TAccountController, TAccessController>(IApplicationBuilder)
  nameWithType: IApplicationBuilderExtensions.UseEforIdentityAuthentication<TKey, TUser, TRole, TSignInManager, TUserManager, TAccountController, TAccessController>(IApplicationBuilder)
  fullName: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforIdentityAuthentication<TKey, TUser, TRole, TSignInManager, TUserManager, TAccountController, TAccessController>(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  type: Method
  source:
    remote:
      path: es.efor.Auth/Extensions/IApplicationBuilderExtensions.cs
      branch: master
      repo: https://dev.azure.com/EforDevelop/Musaat/_git/Musaat_Med
    id: UseEforIdentityAuthentication
    path: ../es.efor.Auth/Extensions/IApplicationBuilderExtensions.cs
    startLine: 25
  assemblies:
  - es.efor.Auth
  namespace: es.efor.Auth.Extensions
  syntax:
    content: >-
      public static IApplicationBuilder UseEforIdentityAuthentication<TKey, TUser, TRole, TSignInManager, TUserManager, TAccountController, TAccessController>(this IApplicationBuilder app)

          where TKey : IEquatable<TKey> where TUser : User<TKey> where TRole : Role<TKey>, new()

          where TSignInManager : IdentitySignInManager<TKey, TUser> where TUserManager : IdentityUserManager<TKey, TUser> where TAccountController : AccountIdentityController<TUser, TKey> where TAccessController : AccessController
    parameters:
    - id: app
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    typeParameters:
    - id: TKey
    - id: TUser
    - id: TRole
    - id: TSignInManager
    - id: TUserManager
    - id: TAccountController
    - id: TAccessController
    return:
      type: Microsoft.AspNetCore.Builder.IApplicationBuilder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseEforIdentityAuthentication(Of TKey As IEquatable(Of TKey), TUser As User(Of TKey), TRole As {Role(Of TKey), New}, TSignInManager As IdentitySignInManager(Of TKey, TUser), TUserManager As IdentityUserManager(Of TKey, TUser), TAccountController As AccountIdentityController(Of TUser, TKey), TAccessController As AccessController)(app As IApplicationBuilder) As IApplicationBuilder
  overload: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforIdentityAuthentication*
  nameWithType.vb: IApplicationBuilderExtensions.UseEforIdentityAuthentication(Of TKey, TUser, TRole, TSignInManager, TUserManager, TAccountController, TAccessController)(IApplicationBuilder)
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforIdentityAuthentication(Of TKey, TUser, TRole, TSignInManager, TUserManager, TAccountController, TAccessController)(Microsoft.AspNetCore.Builder.IApplicationBuilder)
  name.vb: UseEforIdentityAuthentication(Of TKey, TUser, TRole, TSignInManager, TUserManager, TAccountController, TAccessController)(IApplicationBuilder)
references:
- uid: es.efor.Auth.Extensions
  commentId: N:es.efor.Auth.Extensions
  name: es.efor.Auth.Extensions
  nameWithType: es.efor.Auth.Extensions
  fullName: es.efor.Auth.Extensions
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforSimpleAuthentication*
  commentId: Overload:es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforSimpleAuthentication
  name: UseEforSimpleAuthentication
  nameWithType: IApplicationBuilderExtensions.UseEforSimpleAuthentication
  fullName: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforSimpleAuthentication
- uid: Microsoft.AspNetCore.Builder.IApplicationBuilder
  commentId: T:Microsoft.AspNetCore.Builder.IApplicationBuilder
  parent: Microsoft.AspNetCore.Builder
  isExternal: true
  name: IApplicationBuilder
  nameWithType: IApplicationBuilder
  fullName: Microsoft.AspNetCore.Builder.IApplicationBuilder
- uid: Microsoft.AspNetCore.Builder
  commentId: N:Microsoft.AspNetCore.Builder
  isExternal: true
  name: Microsoft.AspNetCore.Builder
  nameWithType: Microsoft.AspNetCore.Builder
  fullName: Microsoft.AspNetCore.Builder
- uid: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforIdentityAuthentication*
  commentId: Overload:es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforIdentityAuthentication
  name: UseEforIdentityAuthentication
  nameWithType: IApplicationBuilderExtensions.UseEforIdentityAuthentication
  fullName: es.efor.Auth.Extensions.IApplicationBuilderExtensions.UseEforIdentityAuthentication
