// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace es.efor.OnBoarding.Data.Entities
{
    public partial class Empresas
    {
        public Empresas()
        {
            Usuarios = new HashSet<Usuarios>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Nombre { get; set; }
        [Required]
        [Column("CIF")]
        [StringLength(50)]
        public string Cif { get; set; }
        [StringLength(50)]
        public string RazonSocial { get; set; }
        public bool Activo { get; set; }
        public int? ResponsableId { get; set; }

        [ForeignKey(nameof(ResponsableId))]
        [InverseProperty("Empresas")]
        public virtual Usuarios Responsable { get; set; }
        [InverseProperty("Empresa")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}