// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace es.efor.OnBoarding.Data.Entities
{
    public partial class Usuarios
    {
        public Usuarios()
        {
            Empresas = new HashSet<Empresas>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Usuario { get; set; }
        [Required]
        [StringLength(50)]
        public string Clave { get; set; }
        [StringLength(50)]
        public string Nombre { get; set; }
        [StringLength(100)]
        public string Apellidos { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        public bool Activo { get; set; }
        public int RoleId { get; set; }
        public int? EmpresaId { get; set; }

        [ForeignKey(nameof(EmpresaId))]
        [InverseProperty("Usuarios")]
        public virtual Empresas Empresa { get; set; }
        [ForeignKey(nameof(RoleId))]
        [InverseProperty(nameof(Roles.Usuarios))]
        public virtual Roles Role { get; set; }
        [InverseProperty("Responsable")]
        public virtual ICollection<Empresas> Empresas { get; set; }
    }
}