// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using es.efor.PryBase.Infraestructure.Database;

namespace es.efor.PryBase.Data.Context
{
    public partial class PryBaseContext : DbContext
    {
        public PryBaseContext()
        {
        }

        public PryBaseContext(DbContextOptions<PryBaseContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Project> Projects { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Project>(entity =>
            {
                entity.HasOne(d => d.Responsable)
                    .WithMany(p => p.Projects)
                    .HasForeignKey(d => d.ResponsableId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Projects_Employees");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}