// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace es.efor.PryBase.Data.Database
{
    public partial class AccessLogger
    {
        public DateTime Date { get; set; }
        public string User { get; set; }
        public Guid? Token { get; set; }
        public int Id { get; set; }
    }
}