// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using es.efor.PryBase.Infraestructure.DTO.Employees;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace es.efor.PryBase.Infraestructure.Database
{
    public partial class Employee
    {
        public Employee()
        {
            Projects = new HashSet<Project>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(25)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Surname { get; set; }
        [Column("DBirth", TypeName = "date")]
        public DateTime Dbirth { get; set; }
        [Column("DStart", TypeName = "date")]
        public DateTime Dstart { get; set; }
        public int? PositionType { get; set; }

        [InverseProperty(nameof(Project.Responsable))]
        public virtual ICollection<Project> Projects { get; set; }
    }
}