// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace es.efor.PryBase.Data.Database
{
    public partial class Employees
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Nif { get; set; }
        public DateTime? BirthDate { get; set; }
        public string Department { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string Headquarters { get; set; }
        public bool? Delete { get; set; }
    }
}