// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace es.efor.PryBase.Data.Database
{
    public partial class UserLevel
    {
        public UserLevel()
        {
            Permissions = new HashSet<Permissions>();
            User = new HashSet<User>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Permissions> Permissions { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}